package com.transloadit.sdk;

import com.transloadit.sdk.exceptions.LocalOperationException;
import com.transloadit.sdk.exceptions.RequestException;
import com.transloadit.sdk.response.Response;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockserver.client.MockServerClient;
import org.mockserver.junit.jupiter.MockServerExtension;
import org.mockserver.junit.jupiter.MockServerSettings;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;

import java.io.IOException;

import static org.mockserver.model.RegexBody.regex;

/**
 * Unit test for {@link Template} class. Api-Responses are simulated by mocking the server's response.
 */
@ExtendWith(MockServerExtension.class)  // MockServerExtension is used to start and stop the MockServer
@MockServerSettings(ports = MockHttpService.PORT) // MockServerSettings is used to define the port of the MockServer
public class TemplateTest extends MockHttpService {

    private final MockServerClient mockServerClient = new MockServerClient("localhost", PORT);

    /**
     * Tests if a new Template returns its correct name by calling {@link Template#getName()}.
     * The name gets defined by its instantiation.
     */


    @Test
    public void getName() {
        Template template = transloadit.newTemplate("foo");
        Assertions.assertEquals(template.getName(), "foo");
    }

    /**
     * Tests functionality of the {@link Template#setName(String)} method. Sets a new name after instantiation of a new
     * {@link Template} object and verifies the result with the {@link Template#getName()} method.
     */
    @Test
    public void setName() {
        Template template = transloadit.newTemplate("foo");
        Assertions.assertEquals(template.getName(), "foo");

        template.setName("bar");
        Assertions.assertEquals(template.getName(), "bar");
    }

    /**
     * Verifies the structure of the POST request to the Transloadit API which gets generated by the
     * {@link Template#save()} method. Also tests if the API response gets parsed correctly.
     * @throws LocalOperationException if building the request goes wrong.
     * @throws RequestException  if communication with the server goes wrong
     * @throws IOException if Test resource "template.json" is missing.
     */
    @Test
    public void save() throws LocalOperationException, RequestException, IOException {
        mockServerClient.when(HttpRequest.request()
                .withPath("/templates").withMethod("POST")
                .withBody(regex("[\\w\\W]*\"name\":\"template_name\"[\\w\\W]*")))
                .respond(HttpResponse.response().withBody(getJson("template.json")));

        Template template = new Template(transloadit, "template_name");
        Response newTemplate = template.save();

        Assertions.assertEquals(newTemplate.json().get("ok"), "TEMPLATE_FOUND");

        mockServerClient.reset();
    }
}
