import org.jetbrains.kotlin.gradle.dsl.JvmTarget

group 'com.transloadit.example'
version '0.0.1'

apply plugin: 'java'
apply plugin: 'kotlin'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation rootProject
    implementation 'io.tus.java.client:tus-java-client:0.5.1'
    implementation 'org.json:json:20231013'
}
buildscript {
    ext.kotlin_version = '1.9.23'
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

compileKotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_1_8)
    }
}
compileTestKotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_1_8)
    }
}

tasks.register('api2DevdockTemplateLifecycle', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.transloadit.examples.Api2DevdockTemplateLifecycle'
}

tasks.register('api2DevdockTusAssembly', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.transloadit.examples.Api2DevdockTusAssembly'
}
